#!/usr/bin/ash
# shellcheck shell=dash

run_hook() {
    /sbin/modprobe -a -q dm-crypt >/dev/null 2>&1
    if [ -e "/sys/class/misc/device-mapper" ]; then
        if [ ! -e "/dev/mapper/control" ]; then
            mkdir /dev/mapper
            mknod "/dev/mapper/control" c $(cat /sys/class/misc/device-mapper/dev | sed 's|:| |')
        fi
        [ "${quiet}" = "y" ] && CSQUIET=">/dev/null"

        if [ -n "${cryptdevice}" ]; then
            DEPRECATED_CRYPT=0
            cryptdev="$(echo "${cryptdevice}" | cut -d: -f1)"
            cryptname="$(echo "${cryptdevice}" | cut -d: -f2)"
            cryptoptions="$(echo "${cryptdevice}" | cut -d: -f3)"
        else
            DEPRECATED_CRYPT=1
            cryptdev="${root}"
            cryptname="root"
        fi

        OLDIFS="${IFS}"
        IFS=","
        for cryptopt in ${cryptoptions}; do
            case ${cryptopt} in
                allow-discards)
                    echo "Enabling TRIM/discard support."
                    cryptargs="${cryptargs} --allow-discards"
                    ;;
                *)
                    echo "Encryption option '${cryptopt}' not known, ignoring." >&2
                    ;;
            esac
        done
        IFS="${OLDIFS}"

        echo ${cryptname} > /.cryptname
        echo ${cryptargs} > /.cryptargs

        if resolved=$(resolve_device "${cryptdev}" ${rootdelay}); then
            echo ${resolved} > /.cryptdev
            echo "Waiting for remote password entry"
            while ! [ -f /.done ]; do
                sleep 0.5
            done    
            rm /.done
         fi
     fi
}
# vim: set ft=sh ts=4 sw=4 et:
